version: '3'
services:
  database:
    image: mysql
    container_name: mysq2
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: examv2thouraya   
    ports:
      - 3306:3306
    networks:
     - AppNet
     
  spring-boot:
    image: eyaghribi/springprojet
    container_name: spring
    ports:
      - 8089:8089
    depends_on:
      - database
    networks:
      - AppNet 
    restart: on-failure     

networks:
  AppNet:
